server:
  port: 8999

eureka:
  instance:
    hostname: localhost


spring:
  application:
    name: ecommerce-apigateway
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
        - id: address-service
          uri: lb://address-service
          predicates:
            - Path=/address/**
